vscode:
  extensions:
    - esbenp.prettier-vscode@3.20.0:37/f4uBlE287wUjENFq1aA==
    - kaiwood.endwise@1.4.2:b9UKVcoO63LrGqSpDkA2mg==
    - castwide.solargraph@0.21.1:kJz6aC6XZbI/EeYHUPNCmQ==
    - bung87.rails@0.16.2:HZRuRl8OsagizSxxVwpESw==